-- Orbit Phase 16: Offerwall expansion for sponsored video/game quests
-- Run after Phase 8 migration.

insert into public.orbit_quests (
  slug,
  title,
  description,
  category,
  action_type,
  reward_starbits,
  target_count,
  repeat_interval_hours,
  sponsor_name,
  sponsor_url,
  sort_order,
  is_active
)
values
  (
    'sponsor-video-winds-meet',
    'Winds Meet Video Quest',
    'Watch the full partner trailer to unlock Starbits reward.',
    'WATCH',
    'WATCH_AD',
    210,
    1,
    24,
    'NetEase',
    'https://www.youtube.com/watch?v=aqz-KE-bpKQ',
    20,
    true
  ),
  (
    'sponsor-video-r6-siege',
    'R6 Siege X Video Quest',
    'Full ad watch required. Partial watch does not grant points.',
    'WATCH',
    'WATCH_AD',
    240,
    1,
    24,
    'Ubisoft',
    'https://www.youtube.com/watch?v=aqz-KE-bpKQ',
    21,
    true
  ),
  (
    'sponsor-video-opera-gx',
    'Opera GX Full Watch',
    'Complete full sponsor clip watch to claim reward.',
    'WATCH',
    'WATCH_AD',
    230,
    1,
    24,
    'Opera GX',
    'https://www.youtube.com/watch?v=aqz-KE-bpKQ',
    22,
    true
  ),
  (
    'sponsor-video-azure-build',
    'Azure Build Quest',
    'Watch partner campaign clip to completion to receive payout points.',
    'WATCH',
    'WATCH_AD',
    250,
    1,
    24,
    'Microsoft Azure',
    'https://www.youtube.com/watch?v=aqz-KE-bpKQ',
    23,
    true
  ),
  (
    'play-steam-trial',
    'Steam Trial Session',
    'Open partner game destination and complete the in-app challenge.',
    'PLAY',
    'PLAY_SESSION',
    280,
    1,
    24,
    'Steam Featured',
    'https://store.steampowered.com',
    30,
    true
  ),
  (
    'play-epic-demo',
    'Epic Demo Quest',
    'Launch the Epic game listing and finish challenge flow for rewards.',
    'PLAY',
    'PLAY_SESSION',
    300,
    1,
    24,
    'Epic Games Store',
    'https://store.epicgames.com',
    31,
    true
  ),
  (
    'play-riot-session',
    'Riot Session Quest',
    'Visit Riot partner page and complete interaction challenge.',
    'PLAY',
    'PLAY_SESSION',
    310,
    1,
    24,
    'Riot Games',
    'https://www.riotgames.com/en',
    32,
    true
  ),
  (
    'play-ubisoft-demo',
    'Ubisoft Demo Sprint',
    'Open Ubisoft partner destination and finish the required challenge.',
    'PLAY',
    'PLAY_SESSION',
    320,
    1,
    24,
    'Ubisoft Connect',
    'https://www.ubisoft.com/en-us/',
    33,
    true
  ),
  (
    'creator-social-share',
    'Creator Social Share',
    'Share one creator clip/post with your server community.',
    'SOCIAL',
    'SOCIAL_SHARE',
    160,
    1,
    24,
    'Creator Partner Program',
    'https://github.com/KlausMikaelson0/orbit',
    40,
    true
  )
on conflict (slug) do update
set
  title = excluded.title,
  description = excluded.description,
  category = excluded.category,
  action_type = excluded.action_type,
  reward_starbits = excluded.reward_starbits,
  target_count = excluded.target_count,
  repeat_interval_hours = excluded.repeat_interval_hours,
  sponsor_name = excluded.sponsor_name,
  sponsor_url = excluded.sponsor_url,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  updated_at = now();
